### ISSUE TITLE
Tall Grass/Fern are uncolored

### ISSUE THREAD

**Issue by MightyKnight** [glisco03/isometric-renders#1]
Hi glisco,
already having fun creating beautiful renders with your mod.
While rendering larger natural areas, I noticed an issue.

Foliage colors don't seem to apply to tall grass and tall fern (double blocks).
<img height=200 src=https://user-images.githubusercontent.com/38622942/120048832-851dc180-c018-11eb-842b-a63e22afa3e8.png></img> <img height=200 src=https://user-images.githubusercontent.com/38622942/120048899-bb5b4100-c018-11eb-92eb-50fd08902184.png></img>

**Steps to reproduce:**
- `/give @s tall_grass`
- Place it down
- Stand in it and use `/isorender area ~ ~ ~ ~ ~1 ~`

➡️ The rendered block will appear gray.

**Comment by glisco03** [comment]
Eyo, thanks for reporting!
This is actually a known issue rooted in the nature of how multi-block scenes are rendered right now and bound to be fixed in a soon-ish update. I was first made aware of this about a week ago and actually wrote the exact code I need to fix it in a separate spin-off mod. I'll integrate that into isorenders probably within the next week or so. I'll leave this open for now as a reminder for me to actually fix it
Cheers

**Comment by glisco03** [comment]
Fixed in latest commit, build available on Discord (or CF as soon as that's back)

**Comment by MightyKnight** [comment]
Great, thank you. Works perfectly with the new commit ;)
Unlikely to join the Discord though, I'm already on way too many servers

**Comment by glisco03** [comment]
Alrighty, glad it works 👌
