### ISSUE TITLE
[FEATURE REQUEST] Crafting Table / Recipe Tooltip

### ISSUE THREAD

**Issue by Coswics** [glisco03/isometric-renders#121]
Mainly for making thumbnails, showing off a high quality version of recipes (for hoplite's legendaries mainly)

**Comment by gliscowo** [comment]
This feature already exists in [Roughly Enough Items](https://modrinth.com/mod/rei), I suggest you use that instead of me duplicating the functionality in Isometric
Cheers

**Comment by Coswics** [comment]
yeah it exists there but not to export it as diff file formats like in iso

**Comment by BraveCaperCat2** [comment]
> This feature already exists in [Roughly Enough Items](https://modrinth.com/mod/rei), I suggest you use that instead of me duplicating the functionality in Isometric Cheers

That can't be used for datapack recipes (and potentially some mods which don't have REI compatibility) that don't use vanilla blocks. For instance, in the TERF datapack, not only are there new crafting table recipes, which aren't displayed to the player if they're on a server without REI, but there are machines which have their own recipes. Most relevant would probably be the fabricator, which has a crafting table-like recipe structure, but uses datapack code to create rather than a normal recipe.
