### ISSUE TITLE
Not find FFmpeg

### ISSUE THREAD

**Issue by KlashRaick** [glisco03/isometric-renders#31]
Hello, I decided to update the build of mods to 1.19 and found that on the new version your mod cannot detect ffmpeg. I checked ffmpeg with the old version and everything was fine.

**Comment by gliscowo** [comment]
Have you made any progress on solving this? The code for detecting FFmpeg is identical in both builds - if it is actually broken on 1.19 for you, it's most likely a compatiblity issue.
Cheers

**Comment by CreeperBuddy227** [comment]
Has any found a solution to this yet? I am assuming that ffmpeg should go into the .minecraft directory.

**Comment by gliscowo** [comment]
Yes it should, you can follow [this tutorial](https://video.stackexchange.com/a/20496) to get it installed in general. Otherwise, simply placing the `ffmpeg.exe` into your .minecraft folder will do the trick. Given that the original issue has now been stale for well over a month, I'll go ahead and close it
Cheers
