### ISSUE TITLE
Large GUI scale overlapping GUI elements

### ISSUE THREAD

**Issue by Tiefseetauchner** [glisco03/isometric-renders#32]
Looks beautiful in Gui Scale 2 (Sodium)

![image](https://user-images.githubusercontent.com/48085877/175815234-2d6bf95a-8cf6-4b28-8a2e-fa774470971f.png)

Not as much in Gui Scale 3

![image](https://user-images.githubusercontent.com/48085877/175815275-3411a79d-3c0f-4f53-b986-97441d56dac6.png)

![image](https://user-images.githubusercontent.com/48085877/175815315-0ba49a21-2a01-4e9d-8b30-b6858d80132e.png)

On a (odd res) 2048x1152 screen, both windowed and fullscreen

I am absolutely incompetent when it comes to most things Minecraft, but if you can (and it's not fixed already, and it's not too much work), make the panels scrollable

Thanks for the mod, loving it (with a magnifying glass cuz I'm blind af)

**Comment by gliscowo** [comment]
Hey, I apprecicate you taking the time to put together such a detailed report. This problem is already known, but not really avoidable without quite a bit of extra code which is why it persists to this day. I do also have good news however, as I'm currently working on a UI framework in a library mod which will hopefully finally allow for this issue to be fixed. So while I can't provide a fix right now, something should hopefully be available soon
Cheers

**Comment by gliscowo** [comment]
I'm happy to report that this has finally been implemented in version [0.4.0](https://modrinth.com/mod/isometric-renders/version/0.4.0%2B1.19). Due to this, Isometric now requires owo-lib, which should be automatically installed by sentinel on first launch. Do note though, the current versions are broken on macOS and will simply make our game appear to be stuck at boot. To fix this, [install owo manually](https://modrinth.com/mod/owo-lib)
Cheers
