### ISSUE TITLE
Transparency and shader support

### ISSUE THREAD

**Issue by MaixGit** [glisco03/isometric-renders#36]
Transparent pixels are appearing where they aren't supposed to be, see below (issue persist with different background colour export settings and different texturepacks). This makes sharing the renders a bit difficult because you either share the 50mb png render or convert to a jpg that can't do transparency. 

Exported png on a red background (#ff0000)
![image](https://user-images.githubusercontent.com/43832909/177496767-88549a89-0e09-447e-8e59-684562fffe4b.png)

Exported png on a dark background (#454545)
![image](https://user-images.githubusercontent.com/43832909/177496621-352b7e67-7878-4e23-bc50-66eef0239fd4.png)

Also just curious if there's a possibility of shader support?

**Comment by chyzman** [comment]
hehehe

**Comment by gliscowo** [comment]
Let me tell you the story of the time I tried to reproduce this issue. It all began in my testing world. Peacefully, in bliss even, I ran the `/isorender area` command. After careful inspection of the preview presented to me by the GUI interface, I decided to export what was shown to me. Given that from my prior experience debugging the "Isometric Renders" mod I *knew* that this bug tends to happen at higher resolutions, I decided that 8000x8000 pixels should be a great choice. Upon pressing the `Clipboard` button, I did not yet realize the consequences of my actions (someone should have told me to "Prepare for unforseen consequences"). Over the next couple of minutes, my personal computing device started its descent into madness. One does not anticipate the unfathomable density of sixty-four million pixels in their clipboard. I have now learned that 1) Your dock will unalive itself 2) A piece of your desktop will permanently render on top of IntelliJ 3) Keyboard input will stop working 4) Mouse input in Krita will be broken, as well as some other observations which I surely have forgotten. As such, a word of warning to everyone planning to handle sixty-four million pixels in their clipboard - do not.

To return to the topic at hand however, this bug is in fact present in vanilla rendering as well - it is not something I can fix. For shader mod support the situation is similar - their pipelines are so distinctly different from vanilla that supporting them essentially means rewriting all rendering code, which I am not currently in the mood to do
Cheers
