### ISSUE TITLE
owo-lib does not install automatically and the game won't start without it

### ISSUE THREAD

**Issue by nnmrts** [glisco03/isometric-renders#44]
In the release notes it is stated that "owo-lib is now a required dependency, installed automatically through sentinel" but when I installed isometric-renders from Modrinth using PolyMC the game wouldn't start and will be stuck at listing the installed mods `Loading 181 mods: ...`.

After I installed owo-lib manually, everything worked again.

**Comment by gliscowo** [comment]
You don't happen to be running macOS?

**Comment by nnmrts** [comment]
@gliscowo I do, macOS Ventura on an M2 machine, why?

**Comment by Noaaan** [comment]
We are already aware of this issue, see https://github.com/wisp-forest/owo-lib/issues/51

**Comment by nnmrts** [comment]
@Noaaan oh, sorry, I missed that one. Can I somehow help with the testing or is this the same old "no macos in GitHub actions" problem?

**Comment by gliscowo** [comment]
The problem here is quite simply that AWT, which sentinel uses, does not work in an MC environment on macOS - something we didn't initially anticipate when developing sentinel. There's a mitigation underway, but for the time being there's nothing you can do to help - we very much appreciate the offer however.
Cheers

**Comment by gliscowo** [comment]
This is now no longer an issue with owo [0.8.3](https://modrinth.com/mod/owo-lib/version/0.8.3%2B1.19)
