### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by aqzsshi** [glisco03/isometric-renders#57]
add version 1.12.2 many servers still support this version and I would like to see this wonderful mod on 1.12.2

**Comment by BasiqueEvangelist** [comment]
https://howoldisminecraft1122.today/

**Comment by gliscowo** [comment]
While it is great to see that you enjoy the mod, I hope you can understand that neither I or anyone else (presumably) will be making any attempts at backporting it. Supporting 1.12 would require not only switching to an entirely different modding toolchain, but also extensive internal rewrites because of how Minecraft's rendering system changed - to the point that you would essentially just be writing a new mod from scratch
