### ISSUE TITLE
[Bug] Area Render not working [Fabric 1.19.2]

### ISSUE THREAD

**Issue by xR4YM0ND** [glisco03/isometric-renders#67]
- Fabric Loader 0.14.19
- Fabric 1.19.2
- Fabric API  0.76.0
- Isometric Renders 0.4.1
- OwO 0.8.5

PS:
can't use 0.9.x cause of crashes
i can select an area with keybinds but when i type `/isorender area` there shows up nothing.

[latest.log](https://gist.github.com/xR4YM0ND/a5737e035602b1847d817c4cabddeca1)

**Comment by gliscowo** [comment]
Incredibly sorry for taking so long to respond

This problem is caused by your version of Fabric API being *too new* - it contains some changes to Indigo which break WorldMesher. You need to downgrade Fabric API to a version before 0.75 ([this one should work](https://modrinth.com/mod/fabric-api/version/0.73.2+1.19.2))

Cheers
