### ISSUE TITLE
Up arrow key not working in signs

### ISSUE THREAD

**Issue by ykvox** [glisco03/isometric-renders#92]
yep, i'm kind of confused too, but this mods messes with the up arrow when editing signs (down arrow works just fine)
thank you in advance !

**Comment by gliscowo** [comment]
Since I have not been able to reproduce this with just Isometric Renders installed, I'd be rather interested to hear how you came to the conclusion that Isometric must be at fault - this is not to say I do not believe your findings, but I rather suspect a conflict with a different mod being the root cause. To this end, please also send me your `latest.log` file from a time you observed the bug

Cheers

**Comment by ykvox** [comment]
this is going to sound incredibly silly..
my keyboard started malfunctioning at the exact moment i was testing your mod 
(and even stopped after launching the game without it)

nothing more than a funny coincidence, i wish you a good day and thank you for your time, it is a fantastic mod btw :)
