### ISSUE TITLE
Fluids Not Rendering

### ISSUE THREAD

**Issue by AriaElidove** [glisco03/isometric-renders#99]
Attempted to render a waterlogged stair and it simply did not show the water. The only work around for this I have found is to do an Area Render instead.

Using v0.4.7 on 1.20.4.

**Comment by gliscowo** [comment]
This isn't really a bug or a missing feature as much as it is a consequence of how waterlogged blocks work. The fluid is indeed not actually part of the block and drawn in an entirely separate stage of terrain rendering - which is why it doesn't show when rendering just the block.

Given how trivial this is to work around by doing single-block area render I also don't see any reason to invest effort into "fixing" it. I will however add a small snippet to the documentation to let users know that they should do that instead

Cheers
